name: media-hub
version: 4.6.0-1
summary: Server and client sides of media-hub
description: |
  Media Hub is a simple and lightweight service for media playback using
  DBus. Please find the source code at:
  https://code.launchpad.net/media-hub
confinement: strict
grade: stable

slots:
  service:
    interface: media-hub
  mpris:
    interface: mpris
    # It works as a parameter to the mpris interface,
    # and gets used to build the apparmor profile
    name: "MediaHub"

plugs:
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

apps:
  media-hub-server:
    command: bin/media-hub-service.wrapper ${SNAP}/usr/bin/media-hub-server
    daemon: simple
    slots: [service]
    plugs: [home, pulseaudio, platform, screen-inhibit-control]
  # ad-hoc until daemon runs as user session
  # Bug for https://bugs.launchpad.net/snappy/+bug/1613420
  media-hub-service:
    command: bin/media-hub-service.wrapper ${SNAP}/usr/bin/media-hub-server
    slots: [service]
    plugs: [home, pulseaudio, platform, screen-inhibit-control]

parts:
  service:
    plugin: cmake
    source: .

    build-packages:
      - build-essential
      - dbus-test-runner
      - debhelper
      - dh-apparmor
      - doxygen
      - google-mock
      - graphviz
      - gstreamer1.0-plugins-good
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-log-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libdbus-1-dev
      - libdbus-cpp-dev
      - libgoogle-glog-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libhybris-dev
      - libprocess-cpp-dev
      - libproperties-cpp-dev
      - libpulse-dev
      - libtelepathy-qt5-dev
      - lsb-release
      - pkg-config
      - qtbase5-dev

    stage-packages:
      # Ok to ship by default since Ubuntu has an mp3 license
      - gstreamer1.0-fluendo-mp3
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-bad-faad
      - gstreamer1.0-plugins-bad-videoparsers
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - gstreamer1.0-pulseaudio
      - xdg-user-dirs
      - mime-support
      - shared-mime-info
    configflags:
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
      - -DCMAKE_LIBRARY_PATH=/usr/lib

    filesets:
      unwanted:
        # Files that we don't want/need in the final snap package
        - -etc
        - -usr/lib/debug
        - -usr/lib/python*
        - -usr/share/apport
        - -usr/share/bug
        - -usr/share/doc
        - -usr/share/fonts
        - -usr/share/libwacom
        - -usr/share/lintian
        - -usr/share/man
        - -usr/share/X11
        - -usr/lib/*.a
        - -usr/lib/*/*.a
        - -usr/lib/*.la
        - -usr/lib/*/*.la
        - -usr/lib/*/*.o
    after:
      - desktop-ubuntu-app-platform

    prime:
      - $unwanted

  # media-hub-overlay includes
  # - ubuntu-app-platform to bind link ubuntu-app-platform snap when connected
  # - bin/media-hub-wrapper to include environment variables
  media-hub-overlay:
    source: overlay/
    plugin: dump
