name: media-hub
version: 4.6.0-1
summary: Server and client sides of media-hub
description: |
  Media Hub is a simple and lightweight service for media playback using
  DBus. Please find the source code at:
  https://code.launchpad.net/media-hub
confinement: strict

slots:
  session-service:
    interface: media-hub
  mpris-service:
    interface: mpris
    name: "MediaHub"

apps:
  media-hub-server:
    command: snappyenv ${SNAP}/usr/bin/media-hub-server
    daemon: simple
    slots: [session-service]
    plugs: [home, pulseaudio]
#ad-hoc until daemon runs as user session
  media-hub-service:
    command: snappyenv ${SNAP}/usr/bin/media-hub-server
    slots: [session-service]
    plugs: [home, pulseaudio]

parts:
  service:
    plugin: cmake
    source: .

    build-packages:
      - build-essential
      - dbus-test-runner
      - debhelper
      - dh-apparmor
      - doxygen
      - google-mock
      - graphviz
      - gstreamer1.0-plugins-good
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-log-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libdbus-1-dev
      - libdbus-cpp-dev
      - libgoogle-glog-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libhybris-dev
      - libprocess-cpp-dev
      - libproperties-cpp-dev
      - libpulse-dev
      - libtelepathy-qt5-dev
      - lsb-release
      - pkg-config
      - qtbase5-dev

    stage-packages:
      # Ok to ship by default since Ubuntu has an mp3 license
      - gstreamer1.0-fluendo-mp3
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-bad-faad
      - gstreamer1.0-plugins-bad-videoparsers
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly-amr
      - gstreamer1.0-pulseaudio
      - xdg-user-dirs
      - locales-all
      - mime-support
      - shared-mime-info
    configflags:
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
      - -DCMAKE_LIBRARY_PATH=/usr/lib

    filesets:
      unwanted:
        # Files that we don't want/need in the final snap package
        - -usr/lib/debug
        - -usr/lib/python*
        - -usr/share/apport
        - -usr/share/bug
        - -usr/share/doc
        - -usr/share/fonts
        - -usr/share/libwacom
        - -usr/share/lintian
        - -usr/share/man
        - -usr/share/X11
        - -usr/lib/*.a
        - -usr/lib/*/*.a
        - -usr/lib/*.la
        - -usr/lib/*/*.la
        - -usr/lib/*/*.o
    after:
      - desktop-ubuntu-app-platform

    snap:
      - $unwanted
  overlay:
    plugin: dump
    source: overlay
